# Generated by Django 6.0.7 on 2026-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_order_manager',
            field=models.BooleanField(default=False),
        ),
    ]
