# Generated by Django 6.0.7 on 2026-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_user_is_order_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Pay with Card'), ('cash', 'Cash on Delivery')], default='card', max_length=10),
        ),
    ]
