# Generated by Django 6.0.7 on 2026-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Store Pickup')], default='home', max_length=10),
        ),
    ]
